export const IDENTITY_ACTION_FAIL = "IDENTITY_ACTION_FAIL";
export const GET_IDENTITY = "GET_IDENTITY";
export const DELETE_IDENTITY = "DELETE_IDENTITY";
export const CREATE_IDENTITY = "CREATE_IDENTITY";
export const GET_ALL_IDENTITY = "GET_ALL_IDENTITY";
export const SET_LOADING = "SET_LOADING";
